### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by marc-soton** [OpenHydrology/OH-Auto-Statistical#10]
The software seems to rely on FEH CDROM outputs.  Does that mean that the opensource outputs will be limited by the FEH commercial terms of conditions which restricts processing of multiple data points, for example?
Are there any other ways of extracting catchment descriptors?
Thanks
Marc

**Comment by faph** [comment]
Simply _using_ the OH Auto Statistical software is not limited by the open source licence. The only thing the licence says that the authors can't guarantee it's correct etc. etc.

Yes, if you use the FEH CD ROM you will be bound by the terms & conditions that come with that software. I'm not a lawyer, but I doubt that the FEH CD T&C say anything about the outputs _you_ create with other software. In fact the OH Auto Statistical _outputs_ are yours and you'll own the full rights to these.

Unfortunately catchment descriptors can currently only be taken from the FEH CD. See also https://github.com/OpenHydrology/CatchmentDescriptors.

**Comment by marc-soton** [comment]
Thanks for the clarification and thanks for making this useful resource available :)
Marc
