### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by neilnutt** [OpenHydrology/OH-Auto-Statistical#3]
Installation of v0.2.0 fails with the following error:

"Windows cannot find 'C:\Program Files\Open Hydrology\OH Auto Statistical\ohenv\Script\pip'.  Make sure you typed the name correctly, and then try again."

I get the same error on all computers that didn't have v0.1.0 installed.  Though the same computers also have likely never had pip either.

**Comment by faph** [comment]
Strange.

Any chance this is Windows 8?

Does it have a `C:\Program Files\Miniconda3` after the installer (partially) completes?

**Comment by faph** [comment]
Have found the bug, my fault. Will publish new release.

**Comment by neilnutt** [comment]
Glad you got the bug. Both win 7 and 8.

**Comment by neilnutt** [comment]
Florenz, retried the installer and still getting the same issue of:

"Windows cannot find 'C:\Program Files\Open Hydrology\OH Auto Statistical\ohenv\Script\pip'. Make sure you typed the name correctly, and then try again."

Browsing to that location the ohenv dir does not exisit and I can't spot any other obvious locations for it.

**Comment by neilnutt** [comment]
Oh and the  C:\Program Files\Miniconda3  directory does exist when it fails.

**Comment by faph** [comment]
Is this a new issue?

**Comment by faph** [comment]
Did you use the installer from https://github.com/OpenHydrology/OH-Auto-Statistical/releases/latest ?

**Comment by neilnutt** [comment]
Yes, I was trying to install v0.2.2 (link above) and is latest version.

**Comment by faph** [comment]
Weird.
- Did it have OH Auto Statistical previously installed?
- Did it have Python previously installed?
- Win7 or Win8? 32 or 64 bit?
- Admin rights ok?
- If Miniconda installed ok, can you execute:
  
  `conda list -p "c:\Program Files\Open Hydrology\OH Auto Statistical\ohvenv"`. 
  
  What's the output?

I'm sure one day we will have a bug-free installer... I really like Miniconda and would like to make it work.

**Comment by neilnutt** [comment]
This was issue with the proxy at my work preventing pip accessing the interent.  Tried at home and the release 0.2.2 installer works correctly.  So not as bad as we thought however 2 things jump out, can pip work behind firewalls and the installer needs to detect that something went wrong (currently reports the installation succeeded).

I think pip can be made to work with a proxy in place but need to set two env variables, http_proxy and https_proxy

http://www.reddit.com/r/Python/comments/2bdxlo/getting_pip_to_work_behind_a_corporate_proxy_on/

**Comment by faph** [comment]
Not very nice of proxies to block pip...

We can use pure conda instead.
